version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: myapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp123
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ../backend
    container_name: myapp-backend
    restart: always
    depends_on:
      - db
    environment:
      # Config Nest para conectarse a MySQL dentro de Docker
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: myapp
      DB_PASSWORD: myapp123
      DB_NAME: myapp

      # Para CORS (lo usamos en main.ts)
      CORS_ORIGIN: http://localhost:8089
    ports:
      - "3000:3000"

  frontend:
    image: nginx:alpine
    container_name: myapp-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8089:80"
    volumes:
      # Sirve la app web compilada de Flutter
      - ../frontend/build/web:/usr/share/nginx/html:ro

volumes:
  db_data:
